export enum ErrorCode {
    UNKNOWN_ERROR = 1000,
    SELLER_PROFILE_ALREADY_EXIST,
    FORBIDDEN,
    INVALID_EMAIL,
    INVALID_ID,
    HASH_SERVICE_ERROR,
    SELLER_PROFILE_IS_APPROVED,
    AADHAAR_IS_ALREADY_VERIFIED,
    CATEGORY_IS_NOT_FOUND,
    CATEGORY_IS_NOT_IN_LEVEL_3,
    INVALID_UPLOAD_FILE_TYPE,
    INVALID_UPLOAD_FILE_MIME_TYPE,
    NO_FILE_TO_UPLOAD,
    UNSUPPORTED_FILE_TYPE,
    UPLOAD_ERROR,
    PRODUCT_KEY_IS_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    BUSINESS_NOT_FOUND,
    BUSINESS_ALREADY_SUBMITTED,
    BUSINESS_ALREADY_APPROVED,
    BUSINESS_NOT_APPROVED,
    INVALID_STATUS_TRANSITION,
    PRODUCT_IS_NOT_FOUND,
    PRODUCT_MEDIA_LIMIT_EXCEEDED,
    INVALID_RETURN_DAYS,
    INVALID_PRODUCT_IMAGE_COUNT,
    INVALID_CATEGORY_LEVEL_2_ID,
    INVALID_CATEGORY_LEVEL_1_ID,
    INVALID_PRODUCT_KEY_ID,
    CANNOT_UPDATE_PUBLISHED_PRODUCT,
    EMPTY_UPDATE_PAYLOAD,
    INVALID_PRODUCT_MEDIA_ID,
    BUSINESS_ID_REQUIRED,
    PRODUCT_NOT_OWNED_BY_BUSINESS,
    ADDRESS_MISMATCH,
    CART_IS_NOT_FOUND,
    CART_ITEM_IS_NOT_FOUND,
    ADDRESS_IS_NOT_THIS_USER,
    PRODUCT_CROSSED_MAX_BUY_COUNT,
    LAYOUT_ALREADY_EXIST,
    LAYOUT_NOT_FOUND,
    INSUFFICIENT_PRODUCT_STOCK,
    ORDER_NOT_FOUND,
    ADDRESS_NOT_FOUND,
}

export const ErrorCodeMessage: Record<ErrorCode, string> = {
    [ErrorCode.UNKNOWN_ERROR]: 'Something went wrong',
    [ErrorCode.SELLER_PROFILE_ALREADY_EXIST]: 'Seller profile is already exist',
    [ErrorCode.FORBIDDEN]: 'You are not allowed to access',
    [ErrorCode.INVALID_EMAIL]: 'Email is invalid',
    [ErrorCode.HASH_SERVICE_ERROR]: 'Failed to hash sensitive data',
    [ErrorCode.SELLER_PROFILE_IS_APPROVED]: 'Seller profile is already approved.',
    [ErrorCode.AADHAAR_IS_ALREADY_VERIFIED]: 'Aadhaar is already verified.',
    [ErrorCode.INVALID_ID]: 'Either id is not present in db or it is invalid',
    [ErrorCode.CATEGORY_IS_NOT_FOUND]: 'Category is not found',
    [ErrorCode.CATEGORY_IS_NOT_IN_LEVEL_3]: 'Category is not in level 3',
    [ErrorCode.INVALID_UPLOAD_FILE_TYPE]: 'Invalid upload file type',
    [ErrorCode.INVALID_UPLOAD_FILE_MIME_TYPE]: 'Invalid upload file mime type',
    [ErrorCode.NO_FILE_TO_UPLOAD]: 'No file to upload',
    [ErrorCode.UNSUPPORTED_FILE_TYPE]: 'Unsupported file type',
    [ErrorCode.UPLOAD_ERROR]: 'Error occurred during file upload',
    [ErrorCode.PRODUCT_KEY_IS_NOT_FOUND]: 'Product key is not found',
    [ErrorCode.INTERNAL_SERVER_ERROR]: 'An internal server error occurred',
    [ErrorCode.BUSINESS_NOT_FOUND]: 'Business not found',
    [ErrorCode.BUSINESS_ALREADY_SUBMITTED]: 'Business is already submitted for verification',
    [ErrorCode.BUSINESS_ALREADY_APPROVED]: 'Business is already approved',
    [ErrorCode.BUSINESS_NOT_APPROVED]: 'Business is not approved',
    [ErrorCode.INVALID_STATUS_TRANSITION]: 'Invalid status transition',
    [ErrorCode.PRODUCT_IS_NOT_FOUND]: 'Product is not found',
    [ErrorCode.PRODUCT_MEDIA_LIMIT_EXCEEDED]: 'Product media limit exceeded',
    [ErrorCode.INVALID_RETURN_DAYS]: 'ReturnDays must be greater than 0 when returnAllowed is true',
    [ErrorCode.INVALID_PRODUCT_IMAGE_COUNT]: 'Product must have between 1 and 10 images',
    [ErrorCode.INVALID_CATEGORY_LEVEL_2_ID]:
        'The provided Category Level 2 ID does not match the parent of the specified Category Level 3 ID',
    [ErrorCode.INVALID_CATEGORY_LEVEL_1_ID]:
        'The provided Category Level 1 ID does not match the parent of the specified Category Level 2 ID',
    [ErrorCode.INVALID_PRODUCT_KEY_ID]: 'One or more provided Product Key IDs are invalid for the specified category',
    [ErrorCode.CANNOT_UPDATE_PUBLISHED_PRODUCT]: 'Cannot update a product that is not in DRAFT status',
    [ErrorCode.EMPTY_UPDATE_PAYLOAD]:
        'At least one of add, update, or deleteIds must be provided to update specifications',
    [ErrorCode.INVALID_PRODUCT_MEDIA_ID]: 'One or more provided Product Media IDs are invalid',
    [ErrorCode.BUSINESS_ID_REQUIRED]: 'Business ID is required in the request headers',
    [ErrorCode.PRODUCT_NOT_OWNED_BY_BUSINESS]: 'Product is not owned by the business',
    [ErrorCode.ADDRESS_MISMATCH]: 'The provided address does not match the cart address',
    [ErrorCode.CART_IS_NOT_FOUND]: 'Cart is not found',
    [ErrorCode.CART_ITEM_IS_NOT_FOUND]: 'Cart item is not found',
    [ErrorCode.ADDRESS_IS_NOT_THIS_USER]: 'The address does not belong to the user',
    [ErrorCode.PRODUCT_CROSSED_MAX_BUY_COUNT]: 'The product has crossed the maximum buy count',
    [ErrorCode.LAYOUT_ALREADY_EXIST]: 'Layout already exist',
    [ErrorCode.LAYOUT_NOT_FOUND]: 'Layout not found',
    [ErrorCode.INSUFFICIENT_PRODUCT_STOCK]: 'Insufficient product stock available',
    [ErrorCode.ORDER_NOT_FOUND]: 'Order not found',
    [ErrorCode.ADDRESS_NOT_FOUND]: 'Address not found',
};
